#! /bin/bash


PROTON_ROOT=${SHACKLETON_ROOT}/libs/qpid-proton


INCLUDES="-I${PROTON_ROOT}/examples/cpp  -I${PROTON_ROOT}/examples/include -I${PROTON_ROOT}/proton-c/include -I${PROTON_ROOT}/proton-c/bindings/cpp/include -I${PROTON_ROOT}/tests/tools/apps/c"

WARNINGS="-Werror -Wall -pedantic-errors -Wno-format -Wno-variadic-macros"

#OPTO=-O3
OPTO=-g



/usr/bin/c++                          \
  -Wno-unused-function                \
  -DPN_HAS_BOOST=1                    \
  ${OPTO}                             \
  -DNDEBUG                            \
  ${INCLUDES}                         \
  -I${PROTON_ROOT}/examples/c/include \
  ${WARNINGS}                         \
  -c ./resource_reporter.c            \
  -o ./resource_reporter.o 





# removed recurring_timer
#for TARGET in simple_send simple_recv direct_send 
for TARGET in recurring_timer  simple_send simple_recv direct_send
do
  echo " "
  echo " "
  echo " "
  echo "target: ${TARGET}"
  echo "compiling..."
  /usr/bin/c++         \
    -DPN_HAS_BOOST=1   \
    ${OPTO}            \
    -DNDEBUG           \
    ${INCLUDES}        \
    ${WARNINGS}        \
    -c ./${TARGET}.cpp \
    -o ./${TARGET}.o


  echo "linking..."
  /usr/bin/c++         \
    ${OPTO}            \
    -DNDEBUG           \
    ./${TARGET}.o  -o ${TARGET} \
    -rdynamic                   \
    ${PROTON_ROOT}/build/proton-c/bindings/cpp/libqpid-proton-cpp.so \
    ${PROTON_ROOT}/build/proton-c/libqpid-proton.so                  \
    ./resource_reporter.o \
    -lssl -lcrypto -lsasl2 -Wl,-rpath,${PROTON_ROOT}/build/proton-c/bindings/cpp:${PROTON_ROOT}/build/proton-c


  echo "built ${TARGET} ."
  echo " "
  echo " "
  echo " "
done


