#! /bin/bash

echo "killing old stuff"
${SHACKLETON_ROOT}/utils/clean_up.sh


export SHACKLETON_ROOT=/home/mick/shackleton

YEAR=`date +%Y`
MONTH=`date +%m`
DAY=`date +%d`
N_CLIENTS=7000


echo -n "starting at: " ; date

test_1.sh ${YEAR} ${MONTH} ${DAY} ${N_CLIENTS}

echo -n "ending at: " ; date


